apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    uid: mimir
    access: proxy
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      timeInterval: "2s"

  - name: Loki
    type: loki
    url: http://loki:3100
    uid: loki
    access: proxy
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
          name: traceId
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    uid: tempo
    access: proxy
    isDefault: false
