name: build jars
on:
  push:
    branches:
      - read-cache-workflow
      # master      
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - "read-cache-workflow"

    paths-ignore:
      - "docs/**"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-jars:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out the repo
        uses: acryldata/sane-checkout-action@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-key: build-jars-cache-key
          cache-read-only: true
      
      - name: Build JARs
        run: |
          ./gradlew jar -x datahub-web-react:jar -x datahub-frontend:jar --parallel --info
      
      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: Build Artifacts
      #     path: |
      #       **/build/libs/*.jar
      #       !**/build/libs/*-sources.jar
      #       !**/build/libs/*-javadoc.jar 