name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
        working-directory: smoke-test/tests/playwright
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: smoke-test/tests/playwright
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: smoke-test/tests/playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: smoke-test/tests/playwright/playwright-report/
          retention-days: 30
